"""Initial migration

Revision ID: 5c7abf5c1c78
Revises: 
Create Date: 2026-02-07 22:45:05.214127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c7abf5c1c78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ml_experiments')
    op.drop_table('delivery_outcomes')
    op.drop_table('training_history')
    op.drop_table('prediction_log')
    op.drop_table('experiment_assignments')
    op.drop_table('model_performance')
    op.drop_table('model_versions')
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_column('route_complexity')
        batch_op.drop_column('driver_experience')
        batch_op.drop_column('success')
        batch_op.drop_column('delay_reason')
        batch_op.drop_column('num_stops')
        batch_op.drop_column('traffic_level')
        batch_op.drop_column('route_distance')
        batch_op.drop_column('is_weekend')
        batch_op.drop_column('day_of_week')
        batch_op.drop_column('temperature')
        batch_op.drop_column('vehicle_type')
        batch_op.drop_column('is_holiday')
        batch_op.drop_column('hour')
        batch_op.drop_column('precipitation')
        batch_op.drop_column('actual_time')
        batch_op.drop_column('actual_distance')
        batch_op.drop_column('estimated_time')
        batch_op.drop_column('driver_id')
        batch_op.drop_column('weather_condition')

    with op.batch_alter_table('route_segments', schema=None) as batch_op:
        batch_op.drop_column('residential_area')
        batch_op.drop_column('safety_class')
        batch_op.drop_column('cctv_coverage')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('population_density')
        batch_op.drop_column('commercial_area')
        batch_op.drop_column('street_width')
        batch_op.drop_column('emergency_response_time')
        batch_op.drop_column('is_weekend')
        batch_op.drop_column('hour')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_segments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hour', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('is_weekend', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('emergency_response_time', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('street_width', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('commercial_area', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('population_density', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('cctv_coverage', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('safety_class', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('residential_area', sa.INTEGER(), server_default=sa.text('0'), nullable=True))

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weather_condition', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('driver_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('estimated_time', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('actual_distance', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('actual_time', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('precipitation', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('hour', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('is_holiday', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('vehicle_type', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('temperature', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('day_of_week', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('is_weekend', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('route_distance', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('traffic_level', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('num_stops', sa.INTEGER(), server_default=sa.text('1'), nullable=True))
        batch_op.add_column(sa.Column('delay_reason', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('success', sa.INTEGER(), server_default=sa.text('1'), nullable=True))
        batch_op.add_column(sa.Column('driver_experience', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('route_complexity', sa.REAL(), nullable=True))

    op.create_table('model_versions',
    sa.Column('version_id', sa.INTEGER(), nullable=True),
    sa.Column('model_name', sa.TEXT(), nullable=False),
    sa.Column('version', sa.TEXT(), nullable=False),
    sa.Column('file_path', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('metrics', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('model_name', 'version')
    )
    op.create_table('model_performance',
    sa.Column('performance_id', sa.INTEGER(), nullable=True),
    sa.Column('model_name', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('num_predictions', sa.INTEGER(), nullable=True),
    sa.Column('mae', sa.REAL(), nullable=True),
    sa.Column('rmse', sa.REAL(), nullable=True),
    sa.Column('accuracy', sa.REAL(), nullable=True),
    sa.Column('feature_drift_score', sa.REAL(), nullable=True),
    sa.Column('prediction_drift_score', sa.REAL(), nullable=True),
    sa.Column('needs_retraining', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('performance_id')
    )
    op.create_table('experiment_assignments',
    sa.Column('assignment_id', sa.INTEGER(), nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), nullable=True),
    sa.Column('entity_id', sa.TEXT(), nullable=True),
    sa.Column('assigned_group', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['ml_experiments.experiment_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('prediction_log',
    sa.Column('log_id', sa.INTEGER(), nullable=True),
    sa.Column('model_name', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('prediction', sa.REAL(), nullable=True),
    sa.Column('actual', sa.REAL(), nullable=True),
    sa.Column('features', sa.TEXT(), nullable=True),
    sa.Column('metadata', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('training_history',
    sa.Column('training_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('models_trained', sa.TEXT(), nullable=True),
    sa.Column('metrics', sa.TEXT(), nullable=True),
    sa.Column('errors', sa.TEXT(), nullable=True),
    sa.Column('version', sa.TEXT(), nullable=True),
    sa.Column('duration_seconds', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('training_id')
    )
    op.create_table('delivery_outcomes',
    sa.Column('outcome_id', sa.INTEGER(), nullable=True),
    sa.Column('delivery_id', sa.INTEGER(), nullable=False),
    sa.Column('start_latitude', sa.REAL(), nullable=True),
    sa.Column('start_longitude', sa.REAL(), nullable=True),
    sa.Column('end_latitude', sa.REAL(), nullable=True),
    sa.Column('end_longitude', sa.REAL(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('traffic_level', sa.REAL(), nullable=True),
    sa.Column('weather', sa.TEXT(), nullable=True),
    sa.Column('route_choice', sa.TEXT(), nullable=True),
    sa.Column('actual_time', sa.REAL(), nullable=True),
    sa.Column('estimated_time', sa.REAL(), nullable=True),
    sa.Column('safety_score', sa.REAL(), nullable=True),
    sa.Column('success', sa.INTEGER(), nullable=True),
    sa.Column('actual_distance', sa.REAL(), nullable=True),
    sa.Column('estimated_distance', sa.REAL(), nullable=True),
    sa.Column('time_reward', sa.REAL(), nullable=True),
    sa.Column('safety_reward', sa.REAL(), nullable=True),
    sa.Column('success_reward', sa.REAL(), nullable=True),
    sa.Column('distance_reward', sa.REAL(), nullable=True),
    sa.Column('total_reward', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('outcome_id')
    )
    op.create_table('ml_experiments',
    sa.Column('experiment_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('model_type', sa.TEXT(), nullable=True),
    sa.Column('version_a', sa.TEXT(), nullable=True),
    sa.Column('version_b', sa.TEXT(), nullable=True),
    sa.Column('traffic_split_a', sa.REAL(), server_default=sa.text('(0.5)'), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'"), nullable=True),
    sa.Column('start_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('experiment_id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
